# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180328_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=52),
        ),
    ]
